name: replicate_interceptor
description: >
  Flutter interceptor package for the Replicate iOS Simulator developer tool
version: 0.1.0+1
homepage: https://canreplicate.app

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  http: ^1.2.0
  dio: ^5.7.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
